# Generated by Django 2.2.8 on 2020-02-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('expense', '0002_expense_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
    ]
